missing keys in settings
elk-zone/elk pull request #1031
Opened 2023-01-12 20:13 UTC by mininaim

2023-01-12 20:42 UTC, jpkhawam commented
@patak-dev looks good 👍🏼 you can merge

2023-01-12 20:43 UTC, jpkhawam commented
@mininaim if you want, you can join the discord and we can have a channel for arabic i18n

2023-01-12 21:53 UTC, mininaim commented
> @mininaim if you want, you can join the discord and we can have a channel for arabic i18n

Hey, the proper use of Arabic and localization within the locales file, still need improvements, specifically with the need for updates on certain words for Arabic users.

Thank you for the suggestion! I would be happy to join Discord and help out with with the Arabic i18n channel.

2023-01-12 21:55 UTC, jpkhawam commented
@mininaim I'd certainly appreciate your input. It was a little hard for me to find all the appropriate words to use

2023-01-14 11:38 UTC, userquin commented
the leading space is required?

![imagen](https://user-images.githubusercontent.com/6311119/212470006-c168d831-a6bd-4317-b177-11342d677976.png)

2023-01-14 17:08 UTC, mininaim commented
> ~the leading space is required?~
> 
> remove space before comma
> 
> ![imagen](https://user-images.githubusercontent.com/6311119/212470006-c168d831-a6bd-4317-b177-11342d677976.png)


Which line? because a word needed a space

2023-01-15 07:45 UTC, shuuji3 requested changes

2023-01-15 07:45 UTC, shuuji3 commented on locales/ar-EG.json
> +      "sponsors_body_1": "تم تمويل Elk من قبل الشركات والأفراد التاليين:" ,
Hello, @mininaim you can just remove the space just before `,` at the end of the line:
```suggestion
      "sponsors_body_1": "تم تمويل Elk من قبل الشركات والأفراد التاليين:",
```

2023-01-15 08:35 UTC, mininaim commented
Apologies, I was using a formatter and I assumed it would automatically
remove the extra space after the comma.

> Message ID: ***@***.***>
>

2023-01-16 12:39 UTC, closed without merging

2023-01-16 12:40 UTC, patak-dev commented
See https://github.com/elk-zone/elk/pull/1217