fix: should hide tooltip when click outside
elk-zone/elk pull request #1123
Opened 2023-01-14 14:51 UTC by webfansplz

Closes #1062

2023-01-14 21:51 UTC, edimitchel commented
This should normally not be needed.
I think we need some @Akryum advice or confirmation it's a bug?

2023-01-15 02:17 UTC, webfansplz commented
> By default tooltips close on mouse out or blur, you shouldn't have to add this logic. Also if you really need it, just put `autoHide`

Thanks.

2023-01-15 02:20 UTC, webfansplz commented
> This should normally not be needed. I think we need some @Akryum advice or confirmation it's a bug?

For #1062, it might make sense to add `autoHide`.

2023-01-15 19:19 UTC, antfu approved these changes

2023-01-15 19:25 UTC, edimitchel approved these changes

2023-01-15 19:25 UTC, edimitchel requested changes

2023-01-15 19:25 UTC, edimitchel commented on components/common/CommonTooltip.vue
> +    :auto-hide="true"
```suggestion
    auto-hide
```

2023-01-15 19:56 UTC, merged