feat: use explorer page as search for mobile only
elk-zone/elk pull request #1301
Opened 2023-01-18 18:09 UTC by edimitchel

### Description

Merge usage of search and explore in one only for mobile or medium screen (could have both search and explore icon active for medium screen).

Resolves #1258
Resolves #894 

![explore-search](https://user-images.githubusercontent.com/2922851/213260213-b7341c9e-d8cf-40c4-bba6-fd0a35c38a37.gif)

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [x] New Feature
- [ ] Documentation update
- [ ] Translations update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/elk-zone/elk/blob/main/CONTRIBUTING.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide related snapshots or videos.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).

2023-01-18 21:31 UTC, edimitchel commented
> As I said on #1274, I think it would make more sense to follow Twitter's example and have the Search icon _replace_ the Explore icon in medium size windows instead of being a redundant link to the same page.

Applied.

2023-01-19 18:06 UTC, antfu approved these changes
Looks nice!

2023-02-03 00:19 UTC, boehs requested changes
I think that "Explore" should be hidden in the mobile submenu, because they are the same page. Otherwise, LGTM

2023-02-03 10:40 UTC, patak-dev commented
Let's merge this one so we avoid the need to resolve conflicts and iterate. I think we'll need to review how this will look if we show search results similar to the timeline more like a dialog for mobile later.

2023-02-03 10:40 UTC, merged

2023-02-03 22:37 UTC, TodePond commented
Hey just to chime in on this - I feel like there should be a setting to toggle this as desired by the user. I really like having 'explore' hidden away, as to not get in the way when just trying to do a simple search. On twitter, I understood why they might want to shove trending posts in my face, but it has been very refreshing to not have that on mastodon.

I think many other people appreciate that about mastodon VS twitter as well :)
Explained a bit further back here: https://github.com/elk-zone/elk/issues/597

Anyone else relate?

2023-02-04 07:52 UTC, patak-dev commented
I agree here, I was also hesitant about making this change but it is good that we tried to get some more data. There were a few messages from folks confused by it on Mastodon. I think we should revert and have to explore and search separately again and let people explicitly go to explore when they want to discover content (I don't use explore at all for example, so I also prefer not to see it).

About having an option to merge them, I think it is better to avoid it for now as we already have too many options, and it isn't clear to me that a lot of people are asking for this.

This PR introduces others changes too that are great (sticky user in the sidebar, etc), @edimitchel let me know if you'd like to send a revert only for the merging part, if not I'll get to it later today or tomorrow

2023-02-04 08:02 UTC, edimitchel commented
I can do a revert but I would like to suggest another thing: on mobile, when search is clicked only show the search input and focus to it.
When focus is lost or scroll is made more than 100px, the search input would be hidden.
Also, I think the search result should not be a popper but should take place on the body.
I'll revert the merge now then work on that feature if it sounds good for you.

2023-02-04 08:07 UTC, patak-dev commented
Yes, I think we can revert then keep exploring how to improve things.

2023-02-04 08:47 UTC, TodePond commented
That sounds like a good plan!

Either way, thanks for putting in time to *explore* these options @edimitchel, I appreciate it! It's useful to see features like this actually implemented, to get a better understanding of them 🙌