feat(180): add spanish `thread` translations
elk-zone/elk pull request #2794
Opened 2024-04-09 20:22 UTC by userquin

/cc @patak-dev @mrcego

2024-04-09 21:00 UTC, mrcego requested changes

2024-04-09 21:00 UTC, mrcego commented on locales/es.json
> +    "add_thread_item": "Agregar otro post al hilo",
Agregar otra publicación al hilo

2024-04-09 21:00 UTC, mrcego commented on locales/es.json
> +    "remove_thread_item": "Eliminar post del hilo",
Eliminar publicación del hilo

2024-04-10 20:02 UTC, emanuelpina approved these changes

2024-04-10 20:25 UTC, merged