feat: update poll
elk-zone/elk pull request #3111
Opened 2024-12-29 13:03 UTC by Cl0v1s

Add an "update poll" option on polls to retrieve the latest results 

![update poll option (french)](https://github.com/user-attachments/assets/68322f0e-25bc-4727-8c4e-4e98947b8094)

![Upodate poll option on hover (french)](https://github.com/user-attachments/assets/0ac36b5a-1562-4323-b1da-3dd49cb0a294)

The refresh icon is animated during loading

2024-12-31 09:49 UTC, shuuji3 reviewed
Thanks, this is a nice addition.

I checked the change with this preview post: https://deploy-preview-3111--elk-zone.netlify.app/universeodon.com/@elkdev/112190894000305452

One comment: once the poll is finalized, it won't be updated anymore, so should we hide the update button after that?

2024-12-31 10:05 UTC, Cl0v1s commented
That could be great indeed. Do you think it would be better to disabled the button or to hide it completely ?

2024-12-31 13:27 UTC, shuuji3 commented
I think hiding it would be better because
1. When the poll has already finished, users won't see the update button so we can avoid making them think it can be updated and they might think there's some issue they cannot click it until they realize the poll was finished at that time.
2. When the poll is still ongoing, users can click the update button to see the latest numbers until it finishes and can know it's finished clearly.

2025-01-03 15:24 UTC, Cl0v1s commented
Will do !

2025-01-03 15:29 UTC, Cl0v1s commented
On second though, there is still the following case: the poll is indeed closed but the local instance did not refetched the results yet (I saw that happening from time to time). Is this a case we should consider ?

2025-01-06 12:01 UTC, shuuji3 commented
That sounds a bit tricky. So in my understanding, there are three phases about the poll state and returned poll data:
1. The poll is still ongoing on remote server, and the local server returns the unfinished poll data.
2. The poll was actually finished on remote server, but the local server returns the outdated poll data.
3. The poll was finished and the local server returns the latest finished poll data.

Since Elk can only send request via masto.js, we can only see the local poll data and we can use either `expired` (boolean) and `expiredAt` (time to finish) props in `Poll` (ref. https://neet.github.io/masto.js/interfaces/mastodon.v1.Poll.html).

So if we compared `expiredAt` with the current time and hide the update button, we shows the wrong state for case 2. That means we need to use `expired` and hide the update button only if its value is `true` (after local server synced the latest poll data).

Do you think my assumption is correct?

2025-01-06 13:00 UTC, Cl0v1s commented
Oh indeed ! That seems perfectly correct, I will change the code according to that last answer :)

2025-01-27 19:17 UTC, Cl0v1s commented
Done !

2025-01-29 02:34 UTC, shuuji3 requested changes

2025-01-29 02:34 UTC, shuuji3 commented on components/status/StatusPoll.vue
> +  loading.value = true
Thanks for the updates!

Before merging, I noticed that "Update poll" button can be clicked multiple times in a short period.

The below change will be able to prevent a new request until Elk receives the response from the server.

```suggestion
  if (loading.value) {
    return
  }

  loading.value = true
```

2025-01-31 03:06 UTC, shuuji3 approved these changes
Thanks, LGTM!

2025-01-31 03:09 UTC, merged